// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZIgFHRIlbd9h-qPS9RlAck0wVQ1A4EMw',
    appId: '1:801707924316:web:5c50b99800d22af8fb3f99',
    messagingSenderId: '801707924316',
    projectId: 'wensa-notification',
    authDomain: 'wensa-notification.firebaseapp.com',
    storageBucket: 'wensa-notification.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSYwab_MWCsJ8wjQLqZmfFxHZc7pWYmnc',
    appId: '1:801707924316:android:5188600c4f67a0bafb3f99',
    messagingSenderId: '801707924316',
    projectId: 'wensa-notification',
    storageBucket: 'wensa-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPN2BcaCiiXgfaTqi4bH9k5HNsY2YDZBg',
    appId: '1:801707924316:ios:9b37a3f97b10fa74fb3f99',
    messagingSenderId: '801707924316',
    projectId: 'wensa-notification',
    storageBucket: 'wensa-notification.firebasestorage.app',
    iosBundleId: 'com.example.wensa',
  );
}
