-- Widen payment_method to admit HyperPay alongside the historical Wayl value.
--
-- 'wayl' is retained and must never be written for a new row: it records which
-- PSP actually took the money for every booking made between 2026-07-31 and
-- this migration. Dropping or rewriting it would destroy that history.
--
-- The constraints added by 20260810080512_add_cash_payment_method.sql were
-- anonymous, so their names were generated by Postgres. Rather than guess at
-- them -- a wrong guess makes DROP CONSTRAINT IF EXISTS a silent no-op and
-- leaves the two-value constraint in force, rejecting 'hyperpay' at runtime --
-- look each one up by its definition and drop whatever is actually there.

DO $$
DECLARE
  tbl   text;
  cname text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['bookings.bookings', 'bookings.memberships'] LOOP
    FOR cname IN
      SELECT conname
        FROM pg_constraint
       WHERE conrelid = tbl::regclass
         AND contype  = 'c'
         AND pg_get_constraintdef(oid) ILIKE '%payment_method%'
    LOOP
      EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', tbl, cname);
      RAISE NOTICE 'dropped % on %', cname, tbl;
    END LOOP;
  END LOOP;
END $$;

ALTER TABLE bookings.bookings
  ADD CONSTRAINT bookings_payment_method_check
    CHECK (payment_method IN ('wayl', 'cash', 'hyperpay'));

ALTER TABLE bookings.memberships
  ADD CONSTRAINT memberships_payment_method_check
    CHECK (payment_method IN ('wayl', 'cash', 'hyperpay'));
